version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 140042960823.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -f Dockerfile -t php-image:v1 .
      - docker tag php-image:v1 140042960823.dkr.ecr.us-east-1.amazonaws.com/my-repository:v1
      - docker push 140042960823.dkr.ecr.us-east-1.amazonaws.com/my-repository:v1
      - echo Build ended on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - printf '[{"name":"myContainerFargate","imageUri":"140042960823.dkr.ecr.us-east-1.amazonaws.com/my-repository@sha256:0e60cfc242ac53b4d8fd50ff1022fe91acdc5f20a871f386139c532fb02068bf"}]' > imagedefinitions.json
artifacts:
    files:
      - '**/*'
      - imagedefinitions.json